package com.yancotv.android.ui.settings

import android.content.Context
import android.content.pm.PackageManager
import androidx.compose.foundation.Image
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.focusable
import androidx.compose.foundation.interaction.MutableInteractionSource
import androidx.compose.foundation.interaction.collectIsFocusedAsState
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.res.pluralStringResource
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.font.Font
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.yancotv.android.R
import com.yancotv.android.prefs.AppPreferences
import com.yancotv.android.ui.focus.snapToTopNearStart
import com.yancotv.android.ui.theme.LocalYancoPalette
import com.yancotv.android.update.UpdateCheckWorker
import com.yancotv.android.update.UpdateInstaller
import com.yancotv.android.update.UpdateRepository
import com.yancotv.shared.update.UpdateCheckOutcome
import com.yancotv.shared.update.UpdateInfo
import kotlinx.coroutines.launch
import org.koin.compose.koinInject

// Stage 5.6 — privacy + terms. This block used to describe URL
// constants awaiting a host; that is no longer how it works and the
// note outlived the code twice, so here is the current shape.
//
// The documents ship INSIDE the APK, as raw resources, and open in
// the same in-app viewer as the licence texts (MB-372). Fire TV has
// no default browser, so an http link was a silent no-op on the
// primary target; bundling also means they are readable offline.
//
// They are localised: res/raw is English, res/raw-ar / -es / -fr are
// the other three. `openRawResource` resolves against the Activity's
// configuration, and LocaleController wraps that context, so the
// in-app language picker selects the document too.
//
// The text is generated by scripts/gen-legal-raw.mjs from the same
// dictionary the website renders, so the published page and the
// bundled copy cannot drift. Edit the site strings, re-run it, commit.
// Hosted copies: yamanaddas.github.io/yancotv-releases/privacy.html
// and /terms.html.

/**
 * About tab — logo + version with an arabesque display face, then a
 * Stage 5.2 Updates section (auto-check toggle, last-checked, "Check
 * now" button + an "update available" banner when the worker has
 * found a newer version).
 *
 * MK.21+ redesign 2026-04-28: replaced the gradient "Y" placeholder
 * + "YancoTV" wordmark + tagline trio with the actual `ic_logo`
 * drawable resized to the same hero footprint, and moved the version
 * label into an arabesque (Cinzel Decorative) face for a more
 * deliberate identity than the default sans.
 *
 * MK.29.5 2026-07-26 superseded the drawable half of that: the hero slot
 * is square, so it takes `ic_logo_mark` — the badge alone — rather than
 * the 16:9 badge+wordmark lockup, which Fit rendered 140x78 inside the
 * square. See the comment at the Image call for the measurements. The
 * arabesque version label is unchanged.
 */
@Composable
fun SettingsAboutTab(
    modifier: Modifier = Modifier,
    prefs: AppPreferences = koinInject(),
    updateRepo: UpdateRepository = koinInject(),
    installer: UpdateInstaller = koinInject(),
) {
    // MB-367 — which bundled licence is open in the viewer, or null.
    var openLicense by androidx.compose.runtime.remember {
        androidx.compose.runtime.mutableStateOf<Pair<String, Int>?>(null)
    }
    openLicense?.let { (title, res) ->
        LicenseViewerDialog(
            title = title,
            textRes = res,
            onDismiss = { openLicense = null },
            // Our own two documents ship translated and unwrapped, so they
            // read in the normal face; the licence texts are verbatim and
            // column-wrapped, so they stay monospace.
            monospace = res != R.raw.privacy_policy && res != R.raw.terms_of_use,
        )
    }

    val ctx = LocalContext.current
    val info = remember { buildInfo(ctx) }
    val scroll = rememberScrollState()
    val palette = LocalYancoPalette.current

    val updatePrefs by prefs.updatePrefsFlow.collectAsState()
    val updateInfo by updateRepo.info.collectAsState()
    val updateCheckOutcome by updateRepo.lastCheck.collectAsState()
    val installerState by installer.state.collectAsState()
    val scope = rememberCoroutineScope()
    val arabesque = remember { FontFamily(Font(R.font.arabesque_display, FontWeight.Bold)) }

    Column(
        modifier =
        modifier
            .fillMaxSize()
            .verticalScroll(scroll)
            // MB-336 — the other missing MK.30.6 retrofit. First focusable
            // (VersionRow) sits 24dp padding + the 140dp logo box down, so
            // up-travel strands ~69dp — half the logo — permanently clipped.
            // Font-scale independent: the offset is dp-fixed, not sp.
            .snapToTopNearStart(scroll)
            .padding(start = 32.dp, end = 32.dp, top = 24.dp, bottom = 80.dp),
        // dpadVerticalScroll deliberately NOT applied here — once the
        // tab has focusable rows (Updates toggle + Check-now button +
        // future control rows), Compose's natural focus traversal
        // drives scrolling automatically. Re-adding it would consume
        // D-pad UP/DOWN before focus could reach the controls, leaving
        // the user unable to hit them. The original MB-116 wrap was
        // for a fully-read-only tab — that's no longer this tab.
    ) {
        // ───── Logo (above the Version block, centered horizontally) ─────
        // MK.29.5 — square 140dp slot, so this takes the badge-only mark.
        // With the 16:9 lockup, Fit rendered it 140x78 inside the square:
        // 44% of the box was empty and the badge was ~35dp wide.
        Image(
            painter = painterResource(id = R.drawable.ic_logo_mark),
            contentDescription = stringResource(R.string.ab_logo_desc, stringResource(R.string.app_name)),
            contentScale = ContentScale.Fit,
            modifier =
            Modifier
                .align(Alignment.CenterHorizontally)
                .size(140.dp)
                .clip(RoundedCornerShape(20.dp))
                .padding(bottom = 12.dp),
        )

        // ───── Version row + tagline ─────
        // No section header — the row IS the version. Reads the real
        // package version (same source as Diagnostics → Build) so it
        // can't drift from what's actually installed.
        VersionRow(text = stringResource(R.string.ab_version_row, info.version), arabesque = arabesque)
        Text(
            text = stringResource(R.string.ab_tagline),
            color = palette.TextMuted,
            fontSize = 12.sp,
            modifier = Modifier.padding(top = 8.dp, bottom = 28.dp),
        )

        // ───── Updates (Stage 5.2.2 + 5.2.3) ─────
        // When BuildConfig.UPDATE_ENDPOINT is empty (no `update.endpoint`
        // in local.properties — the default for dev builds) the checker
        // is an unconditional no-op. Surface that explicitly instead of
        // showing a "Check now" button that does nothing + a "Last
        // checked: Just now" timestamp that lies. UpdateRepository
        // mirrors this state from UpdateChecker.isConfigured.
        val isConfigured = updateRepo.isConfigured
        val updatesSub =
            if (isConfigured) {
                stringResource(R.string.ab_updates_on)
            } else {
                stringResource(R.string.ab_updates_off)
            }
        val updatesRight: (@Composable () -> Unit)? =
            if (isConfigured) {
                {
                    SettingsOutlinedButton(
                        onClick = {
                            scope.launch {
                                updateRepo.triggerCheckOutcome()
                            }
                        },
                        enabled = updateCheckOutcome != UpdateCheckOutcome.Checking,
                        size = ButtonSize.Compact,
                    ) {
                        Text(
                            text =
                            if (updateCheckOutcome == UpdateCheckOutcome.Checking) {
                                stringResource(R.string.ab_checking)
                            } else {
                                stringResource(R.string.ab_check_now)
                            },
                        )
                    }
                }
            } else {
                null
            }
        SettingsSection(
            title = stringResource(R.string.ab_sec_updates),
            sub = updatesSub,
            right = updatesRight,
        ) {
            if (!isConfigured) {
                // Nothing else makes sense here — the toggle would be a
                // dead control, the timestamp would be permanently
                // "Never" or stale. Leave the section visible so the
                // user knows the feature exists; the sub copy explains
                // why the controls are absent.
                return@SettingsSection
            }
            SettingsToggleRow(
                label = stringResource(R.string.ab_auto_check),
                description = stringResource(R.string.ab_auto_check_desc),
                checked = updatePrefs.autoCheckEnabled,
                onCheckedChange = { enabled ->
                    scope.launch {
                        prefs.setAutoUpdateCheckEnabled(enabled)
                        if (enabled) {
                            UpdateCheckWorker.schedulePeriodic(ctx)
                        } else {
                            UpdateCheckWorker.cancelPeriodic(ctx)
                        }
                    }
                },
            )
            SettingsRowSpacer()
            SettingsRow(
                label = stringResource(R.string.ab_last_checked),
                right = { ValueText(formatLastChecked(updatePrefs.lastCheckedAt)) },
            )
            updateCheckOutcome
                ?.takeUnless { it is UpdateCheckOutcome.Available && updateInfo != null }
                ?.let { outcome ->
                    SettingsRowSpacer()
                    UpdateCheckFeedbackRow(outcome = outcome)
                }
            updateInfo?.let { uinfo ->
                SettingsRowSpacer()
                UpdateAvailableBanner(
                    info = uinfo,
                    installerState = installerState,
                    onDownload = { installer.download(uinfo) },
                    onCancel = { installer.cancel() },
                    onInstall = { apk ->
                        // launchInstall returns false when the system "install
                        // unknown apps" permission isn't granted yet — it
                        // also routes the user to settings, so the UI can
                        // surface a hint without opening anything itself.
                        installer.launchInstall(apk)
                    },
                    onRetry = {
                        installer.reset()
                        installer.download(uinfo)
                    },
                    onOpenReleasePage = {
                        runCatching {
                            ctx.startActivity(
                                android.content.Intent(
                                    android.content.Intent.ACTION_VIEW,
                                    android.net.Uri.parse(uinfo.downloadUrl),
                                ).addFlags(android.content.Intent.FLAG_ACTIVITY_NEW_TASK),
                            )
                        }
                    },
                )
            }
        }

        // ───── About YancoTV ─────
        // Replaces the previous "Credits" section, which was a developer
        // architecture lecture (mentioning packages/shared, milestone
        // codes, etc — none of which mean anything to users). One human
        // sentence about what the app does + who it's for.
        SettingsSection(
            title = stringResource(R.string.ab_sec_about),
            sub = stringResource(R.string.ab_blurb),
        ) {}

        // ───── Privacy ─────
        // Stage 5.6. The crash-reports toggle is the user-facing surface
        // for the Sentry pipeline disclosed in the privacy policy — we
        // can't credibly say "you can opt out" unless we ship a switch
        // that actually does it. The switch flips a shared preference
        // (`CrashReportPrefs`); Sentry's `beforeSend` callback consults
        // it on every event, so future crashes / breadcrumbs are dropped
        // at the SDK boundary the moment it's toggled off.
        //
        // Privacy + Terms links open the user-published HTTPS docs in a
        // browser (or the system's default link handler). Until those
        // are hosted, the URLs in PrivacyPolicyUrl / TermsOfServiceUrl
        // point at placeholders — easy to swap to real URLs once the
        // docs go up. Doing this now means the v1 APK already has the
        // right hooks; we only have to host two HTML files later.
        var crashReportsEnabled by remember {
            mutableStateOf(
                com.yancotv.android.crash.CrashReportPrefs.isEnabled(ctx),
            )
        }
        SettingsSection(
            title = stringResource(R.string.ab_sec_privacy),
            sub = stringResource(R.string.ab_privacy_sub),
        ) {
            SettingsToggleRow(
                label = stringResource(R.string.ab_crash_reports),
                description = stringResource(R.string.ab_crash_desc),
                checked = crashReportsEnabled,
                onCheckedChange = { enabled ->
                    crashReportsEnabled = enabled
                    com.yancotv.android.crash.CrashReportPrefs.setEnabled(ctx, enabled)
                },
            )
            SettingsRowSpacer()
            // MB-372 — these opened https://example.invalid/... (an RFC 2606
            // reserved-to-never-resolve placeholder) in a browser Fire TV
            // does not even have. The documents now ship in the APK and open
            // in the same viewer as the licences: correct on TV, correct
            // offline, and nothing depends on pages that were never hosted.
            SettingsRow(
                label = stringResource(R.string.ab_privacy_policy),
                readOnlyFocusable = false,
                onClick = {
                    openLicense = ctx.getString(R.string.ab_privacy_policy) to R.raw.privacy_policy
                },
                right = { ValueText(stringResource(R.string.ab_open)) },
            )
            SettingsRowSpacer()
            SettingsRow(
                label = stringResource(R.string.ab_terms),
                onClick = {
                    openLicense = ctx.getString(R.string.ab_terms) to R.raw.terms_of_use
                },
                right = { ValueText(stringResource(R.string.ab_open)) },
            )
        }

        // MB-367 — open-source attribution. The app ships LGPL-3.0 FFmpeg
        // (both the ffmpeg-kit shared libraries and a vendored JNI shim that
        // statically links FFmpeg) plus a large Apache-2.0 stack; until this
        // section existed there was no acknowledgement anywhere in the app.
        // Rows link to the canonical licence texts rather than bundling
        // them: a bundled text must be VERBATIM, and hand-typing licence
        // text is exactly how subtle corruption ships. The FFmpeg row also
        // points at the source repository, which carries the shim's Java
        // sources and the documented build recipe -- the LGPL relink
        // material for the statically linked part.
        SettingsSection(
            title = stringResource(R.string.ab_sec_licenses),
            sub = stringResource(R.string.ab_licenses_sub),
        ) {
            SettingsRow(
                label = "FFmpeg",
                hint = stringResource(R.string.ab_ffmpeg_hint),
                // In-app viewer, not a browser link: Fire TV ships no
                // default browser, so ACTION_VIEW http is a silent no-op on
                // the primary target. Verbatim text bundled from gnu.org.
                onClick = { openLicense = "FFmpeg — GNU LGPL-3.0" to R.raw.license_lgpl_3_0 },
                right = { ValueText("LGPL-3.0") },
            )
            SettingsRowSpacer()
            SettingsRow(
                label = stringResource(R.string.ab_ffmpeg_sources),
                hint = stringResource(R.string.ab_ffmpeg_sources_hint),
                onClick = { openUrl(ctx, "https://github.com/YamanAddas/YancoTV") },
                right = { ValueText(stringResource(R.string.ab_open)) },
            )
            SettingsRowSpacer()
            SettingsRow(
                label = "Media3, OkHttp, Ktor, Kotlin, Compose, SQLDelight, Koin, Coil, kotlinx",
                hint = stringResource(R.string.ab_apache_hint),
                onClick = { openLicense = "Apache License 2.0" to R.raw.license_apache_2_0 },
                right = { ValueText("Apache-2.0") },
            )
            SettingsRowSpacer()
            SettingsRow(
                label = "Sentry SDK",
                onClick = { openLicense = "Sentry SDK — MIT" to R.raw.license_sentry_mit },
                right = { ValueText("MIT") },
            )
            SettingsRowSpacer()
            // ffmpeg-kit's TLS build ships these inside the AAR as raw
            // resources already — GnuTLS and GMP are LGPL components in the
            // APK, so they get named here too, reading the texts the
            // library itself bundled.
            SettingsRow(
                label = "GnuTLS",
                onClick = { openLicense = "GnuTLS — GNU LGPL" to com.arthenica.ffmpegkit.R.raw.license_gnutls },
                right = { ValueText("LGPL") },
            )
            SettingsRowSpacer()
            SettingsRow(
                label = "GMP",
                onClick = { openLicense = "GMP — GNU LGPL" to com.arthenica.ffmpegkit.R.raw.license_gmp },
                right = { ValueText("LGPL") },
            )
            SettingsRowSpacer()
            SettingsRow(
                label = "Nettle",
                onClick = { openLicense = "Nettle" to com.arthenica.ffmpegkit.R.raw.license_nettle },
                right = { ValueText("LGPL/GPL2+") },
            )
            SettingsRowSpacer()
            SettingsRow(
                label = "libiconv",
                onClick = { openLicense = "libiconv — GNU LGPL" to com.arthenica.ffmpegkit.R.raw.license_libiconv },
                right = { ValueText("LGPL") },
            )
        }

        // ───── Diagnostics ─────
        // Renamed from "Build" — these are debugging fields, not user
        // identity. Combined version + build into one row, dropped the
        // useless "Package: com.yancotv.android" row, added a Device
        // row that's actually useful when filing a bug report. Each
        // row is readOnlyFocusable so D-pad walks the whole tab top-
        // to-bottom and the verticalScroll's bringIntoView pulls each
        // focused row into the safety-margin gap inherited from
        // SettingsScreen (MK.21.8) — focus + scroll integrated, not
        // bolted together.
        SettingsSection(
            title = stringResource(R.string.ab_sec_diagnostics),
            sub = stringResource(R.string.ab_sec_diagnostics_sub),
        ) {
            SettingsRow(
                label = stringResource(R.string.ab_build),
                readOnlyFocusable = true,
                right = {
                    ValueText(stringResource(R.string.ab_build_value, info.version, info.versionCode))
                },
            )
            SettingsRowSpacer()
            SettingsRow(
                label = stringResource(R.string.ab_device),
                readOnlyFocusable = true,
                right = {
                    ValueText(
                        stringResource(
                            R.string.ab_device_value,
                            android.os.Build.MODEL,
                            android.os.Build.VERSION.RELEASE,
                        ),
                    )
                },
            )
        }
    }
}

@Composable
private fun UpdateCheckFeedbackRow(outcome: UpdateCheckOutcome) {
    val (label, hint) =
        when (outcome) {
            UpdateCheckOutcome.Disabled ->
                stringResource(R.string.ab_upd_unavailable) to
                    stringResource(R.string.ab_upd_unavailable_sub)
            UpdateCheckOutcome.Checking ->
                stringResource(R.string.ab_upd_checking) to
                    stringResource(R.string.ab_upd_checking_sub)
            is UpdateCheckOutcome.UpToDate ->
                stringResource(R.string.ab_upd_latest) to
                    stringResource(
                        R.string.ab_upd_latest_sub,
                        outcome.versionName,
                        outcome.versionCode,
                    )
            // `outcome.reason` is provider/transport text — untranslatable
            // by nature, same rule as SyncDetail.Failure (MK.31.18).
            is UpdateCheckOutcome.Failed ->
                stringResource(R.string.ab_upd_failed) to outcome.reason
            is UpdateCheckOutcome.Available ->
                stringResource(R.string.ab_upd_found) to
                    stringResource(R.string.ab_upd_found_sub, outcome.info.versionName)
        }
    SettingsRow(
        label = label,
        hint = hint,
        readOnlyFocusable = true,
    )
}

/**
 * Custom focusable version row — visually matches `SettingsRow` but
 * lets the label render in the arabesque face. Used only on the
 * About hero's Version block. Drives D-pad traversal + bringIntoView
 * scroll the same way every other read-only-focusable row does.
 */
@Composable
private fun VersionRow(text: String, arabesque: FontFamily) {
    val palette = LocalYancoPalette.current
    val interaction = remember { MutableInteractionSource() }
    val focused by interaction.collectIsFocusedAsState()
    val shape = RoundedCornerShape(12.dp)
    Row(
        modifier =
        Modifier
            .fillMaxWidth()
            .clip(shape)
            .background(palette.BackgroundRaised.copy(alpha = if (focused) 0.65f else 0.5f))
            .border(
                width = if (focused) 1.5.dp else 1.dp,
                color = if (focused) palette.FocusRing else palette.BorderSubtle,
                shape = shape,
            )
            .focusable(interactionSource = interaction)
            .padding(horizontal = 22.dp, vertical = 16.dp),
        verticalAlignment = Alignment.CenterVertically,
    ) {
        Text(
            text = text,
            color = palette.TextPrimary,
            fontSize = 16.sp,
            fontWeight = FontWeight.Bold,
            fontFamily = arabesque,
            letterSpacing = 0.4.sp,
            modifier = Modifier.weight(1f),
        )
    }
}

@Composable
private fun ValueText(value: String) {
    Text(
        text = value,
        color = LocalYancoPalette.current.TextPrimary,
        fontSize = 14.sp,
        fontWeight = FontWeight.SemiBold,
    )
}

/**
 * Stage 5.2.3 — banner that surfaces whenever the [UpdateRepository]
 * has a known new version. Drives off [UpdateInstaller.State] so the
 * call-to-action morphs as the user steps through the flow:
 *
 *   - Idle               → "Download update" (+ "Open release page")
 *   - Downloading(pct)   → progress bar + "Cancel"
 *   - ReadyToInstall     → "Install now" (+ "Open release page")
 *   - Failed(reason)     → reason text + "Retry" (+ "Open release page")
 *
 * The release-page button stays available in every state as a fallback
 * — if our download host is down, or the user prefers their browser,
 * they can sideload manually.
 */
@Composable
private fun UpdateAvailableBanner(
    info: UpdateInfo,
    installerState: UpdateInstaller.State,
    onDownload: () -> Unit,
    onCancel: () -> Unit,
    onInstall: (java.io.File) -> Unit,
    onRetry: () -> Unit,
    onOpenReleasePage: () -> Unit,
) {
    val palette = LocalYancoPalette.current
    Box(
        modifier =
        Modifier
            .fillMaxWidth()
            .padding(horizontal = 16.dp, vertical = 8.dp)
            .clip(RoundedCornerShape(10.dp))
            .background(palette.Accent.copy(alpha = 0.12f))
            .padding(horizontal = 14.dp, vertical = 12.dp),
    ) {
        Column {
            Text(
                text = stringResource(R.string.ab_new_version, info.versionName),
                color = palette.Accent,
                fontSize = 14.sp,
                fontWeight = FontWeight.SemiBold,
            )
            val notes = info.releaseNotes
            if (!notes.isNullOrBlank()) {
                Text(
                    text = notes,
                    color = palette.TextSecondary,
                    fontSize = 12.sp,
                    modifier = Modifier.padding(top = 4.dp),
                )
            }

            when (val s = installerState) {
                UpdateInstaller.State.Idle -> {
                    Text(
                        text = stringResource(R.string.ab_update_choice),
                        color = palette.TextMuted,
                        fontSize = 12.sp,
                        modifier = Modifier.padding(top = 6.dp, bottom = 10.dp),
                    )
                    Row {
                        SettingsOutlinedButton(
                            onClick = onDownload,
                            size = ButtonSize.Compact,
                        ) {
                            Text(text = stringResource(R.string.ab_download_update))
                        }
                        Spacer(modifier = Modifier.width(12.dp))
                        SettingsOutlinedButton(
                            onClick = onOpenReleasePage,
                            size = ButtonSize.Compact,
                        ) {
                            Text(text = stringResource(R.string.ab_open_release))
                        }
                    }
                }
                is UpdateInstaller.State.Downloading -> {
                    Text(
                        text = stringResource(R.string.ab_downloading, s.percent),
                        color = palette.TextSecondary,
                        fontSize = 12.sp,
                        modifier = Modifier.padding(top = 6.dp, bottom = 8.dp),
                    )
                    LinearProgressBar(percent = s.percent)
                    Spacer(modifier = Modifier.height(10.dp))
                    SettingsOutlinedButton(
                        onClick = onCancel,
                        size = ButtonSize.Compact,
                    ) {
                        Text(text = stringResource(R.string.common_cancel))
                    }
                }
                is UpdateInstaller.State.ReadyToInstall -> {
                    Text(
                        text = stringResource(R.string.ab_download_done),
                        color = palette.TextMuted,
                        fontSize = 12.sp,
                        modifier = Modifier.padding(top = 6.dp, bottom = 10.dp),
                    )
                    Row {
                        SettingsOutlinedButton(
                            onClick = { onInstall(s.apkFile) },
                            size = ButtonSize.Compact,
                        ) {
                            Text(text = stringResource(R.string.ab_install_now))
                        }
                        Spacer(modifier = Modifier.width(12.dp))
                        SettingsOutlinedButton(
                            onClick = onOpenReleasePage,
                            size = ButtonSize.Compact,
                        ) {
                            Text(text = stringResource(R.string.ab_open_release))
                        }
                    }
                }
                is UpdateInstaller.State.Failed -> {
                    Text(
                        text = stringResource(R.string.ab_download_failed, s.reason),
                        color = palette.TextSecondary,
                        fontSize = 12.sp,
                        modifier = Modifier.padding(top = 6.dp, bottom = 10.dp),
                    )
                    Row {
                        SettingsOutlinedButton(
                            onClick = onRetry,
                            size = ButtonSize.Compact,
                        ) {
                            Text(text = stringResource(R.string.ab_retry))
                        }
                        Spacer(modifier = Modifier.width(12.dp))
                        SettingsOutlinedButton(
                            onClick = onOpenReleasePage,
                            size = ButtonSize.Compact,
                        ) {
                            Text(text = stringResource(R.string.ab_open_release))
                        }
                    }
                }
            }
        }
    }
}

@Composable
private fun LinearProgressBar(percent: Int) {
    val palette = LocalYancoPalette.current
    val pct = percent.coerceIn(0, 100)
    Box(
        modifier =
        Modifier
            .fillMaxWidth()
            .height(6.dp)
            .clip(RoundedCornerShape(3.dp))
            .background(palette.BorderSubtle.copy(alpha = 0.6f)),
    ) {
        Box(
            modifier =
            Modifier
                .fillMaxWidth(fraction = pct / 100f)
                .height(6.dp)
                .clip(RoundedCornerShape(3.dp))
                .background(palette.Accent),
        )
    }
}

// MK.31.7 — @Composable so the buckets can resolve resources. Only caller is
// the "Last checked" row, which is already in composable scope. The
// bucket boundaries stay pure arithmetic; only the rendering is localized.
@Composable
private fun formatLastChecked(millis: Long?): String {
    if (millis == null) return stringResource(R.string.time_never)
    val deltaMs = System.currentTimeMillis() - millis
    // A negative delta means the clock moved backwards (NTP correction,
    // manual change) — report it as "just now" rather than a huge value.
    if (deltaMs < 0L) return stringResource(R.string.time_just_now)
    val mins = deltaMs / 60_000L
    return when {
        mins < 1L -> stringResource(R.string.time_just_now)
        mins < 60L -> stringResource(R.string.time_min_ago, mins)
        mins < 24L * 60L ->
            pluralStringResource(R.plurals.time_hr_ago, (mins / 60L).toInt(), mins / 60L)
        else -> stringResource(R.string.time_d_ago, mins / (24L * 60L))
    }
}

private data class BuildInfo(val version: String, val versionCode: Long, val packageName: String)

private fun buildInfo(ctx: Context): BuildInfo {
    val pm = ctx.packageManager
    val pkg = ctx.packageName
    return try {
        val info = pm.getPackageInfo(pkg, 0)

        @Suppress("DEPRECATION")
        val code: Long =
            if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.P) {
                info.longVersionCode
            } else {
                info.versionCode.toLong()
            }
        BuildInfo(
            version = info.versionName ?: "?",
            versionCode = code,
            packageName = pkg,
        )
    } catch (_: PackageManager.NameNotFoundException) {
        BuildInfo(version = "?", versionCode = 0L, packageName = pkg)
    }
}

private fun openUrl(ctx: android.content.Context, url: String) {
    runCatching {
        ctx.startActivity(
            android.content.Intent(
                android.content.Intent.ACTION_VIEW,
                android.net.Uri.parse(url),
            ).addFlags(android.content.Intent.FLAG_ACTIVITY_NEW_TASK),
        )
    }
}
