package com.yancotv.shared.backup

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFails
import kotlin.test.assertNotEquals
import kotlin.test.assertTrue

/**
 * Cross-target parity for [BackupCipher] and [sha256Hex].
 *
 * These live in `commonTest` on purpose: every target compiles and runs
 * them against its own `actual`. A password-protected backup exported on
 * Android must restore on iOS and vice versa, so the KDF, the cipher and
 * the on-disk layout have to agree byte for byte — not merely
 * "round-trip on the platform that wrote them".
 *
 * ### Provenance of the vectors
 *
 * - `PBKDF2_C1` / `PBKDF2_C4096` are the published PBKDF2-HMAC-SHA256
 *   vectors for `P="password", S="salt", dkLen=32`. They are third-party
 *   ground truth, not a recording of our own output, so they pin both
 *   implementations to the standard rather than to each other.
 * - `PBKDF2_UNICODE` and the `GCM_*` blobs were generated by the JVM /
 *   Android `actual` (the shipped, tested implementation) and are pinned
 *   here so any other target must reproduce them exactly.
 *
 * `encryptHex` draws a fresh random IV per call, so it cannot be pinned
 * directly — the fixed vectors exercise [BackupCipher.decryptBytes] and
 * a round-trip covers the encrypt direction.
 */
class BackupCipherParityTest {

    private val cipher = BackupCipher()

    /** Hex of the ASCII bytes of "salt". */
    private val saltHex = "73616c74"

    private val arabic = "كلمة السر"

    private fun ByteArray.hex(): String = joinToString("") { ((it.toInt() and 0xFF) + 0x100).toString(16).substring(1) }

    // ---- SHA-256 ----------------------------------------------------

    @Test
    fun sha256_matchesKnownVectors() {
        assertEquals("e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", sha256Hex(ByteArray(0)))
        assertEquals("ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad", sha256Hex("abc".encodeToByteArray()))
    }

    /**
     * Empty input is a real path: BackupImporter checksums the records
     * array, which is empty for a backup with nothing in it. On
     * Kotlin/Native this is also the case that cannot take the normal
     * `Pinned.addressOf(0)` route.
     */
    @Test
    fun sha256_handlesEmptyInput() {
        assertEquals(64, sha256Hex(ByteArray(0)).length)
    }

    /** Pins UTF-8 encoding through the hash path. */
    @Test
    fun sha256_isUtf8Stable() {
        assertEquals("31395b1d99f29be434abadfa467fa074c8bf319726f4d3cfe4bcbc670b5ca60e", sha256Hex(arabic.encodeToByteArray()))
    }

    // ---- PBKDF2 -----------------------------------------------------

    @Test
    fun deriveKey_matchesPublishedVectors() {
        assertEquals("120fb6cffcf8b32c43e7225256c4f837a86548c92ccc35480805987cb70be17b", cipher.deriveKey("password", saltHex, 1).hex())
        assertEquals("c5e478d59288c841aa530db6845c4c8d962893a001ce4e11a4963873aa98134a", cipher.deriveKey("password", saltHex, 4096).hex())
    }

    /**
     * The highest-risk parity assertion in the file. Android derives from
     * `PBEKeySpec(CharArray)`; iOS feeds `password.encodeToByteArray()` to
     * `CCKeyDerivationPBKDF`. Those agree only because the JCE encodes the
     * password as UTF-8 — if that assumption is ever wrong, a non-ASCII
     * password silently derives a different key and the backup is
     * unrecoverable. An ASCII-only vector would not catch it.
     */
    @Test
    fun deriveKey_isUtf8StableForNonAsciiPasswords() {
        assertEquals("e6ef83a854847dafb5aabd129caebac169312a71560e9dcdfa876eba6a0eb376", cipher.deriveKey(arabic, saltHex, 1000).hex())
    }

    @Test
    fun deriveKey_producesA256BitKey() {
        assertEquals(32, cipher.deriveKey("password", saltHex, 1).size)
    }

    @Test
    fun deriveKey_rejectsEmptySalt() {
        assertFails { cipher.deriveKey("password", "", 1) }
    }

    @Test
    fun deriveKey_rejectsOutOfRangeIterations() {
        assertFails { cipher.deriveKey("password", saltHex, 0) }
        assertFails { cipher.deriveKey("password", saltHex, 1_000_001) }
    }

    // ---- AES-256-GCM ------------------------------------------------

    /**
     * The interop test. This blob was produced by the Android `actual`;
     * decrypting it proves a different platform reads Android's layout of
     * `iv(12) || ciphertext || tag(16)`.
     */
    @Test
    fun decryptBytes_readsAFixedAndroidProducedVector() {
        val key = cipher.deriveKey("password", saltHex, 1)
        val vector = "01ed42c927e0fc8b7e5ad3f6d99018af6e9b5664dfa2230a53bca91e610cfd94e55fe654e2b670be"
        assertEquals("hello backup", cipher.decryptBytes(vector, key).decodeToString())
    }

    /** 12-byte IV + 12-byte ciphertext + 16-byte tag = 40 bytes = 80 hex chars. */
    @Test
    fun fixedVector_hasTheExpectedWireLayout() {
        val vector = "01ed42c927e0fc8b7e5ad3f6d99018af6e9b5664dfa2230a53bca91e610cfd94e55fe654e2b670be"
        assertEquals((12 + 12 + 16) * 2, vector.length)
    }

    /**
     * Zero-length plaintext is legal in GCM and yields a bare tag. On
     * Kotlin/Native it short-circuits the CTR keystream entirely — the
     * tag is computed over an empty ciphertext plus the lengths block.
     */
    @Test
    fun decryptBytes_readsAFixedEmptyPlaintextVector() {
        val key = cipher.deriveKey("password", saltHex, 1)
        val vector = "055aea70715c4e3407d8719c7acc2380467b5fca5fb0996721c9b278"
        assertEquals((12 + 0 + 16) * 2, vector.length)
        assertEquals(0, cipher.decryptBytes(vector, key).size)
    }

    /**
     * Published AES-256-GCM reference vectors — McGrew & Viega, "The
     * Galois/Counter Mode of Operation", test cases 13 and 14 (the pair
     * every mainstream implementation pins). Third-party ground truth
     * for the cipher itself, complementing the Android-produced interop
     * blob above: these pin both actuals to the *standard*, not merely
     * to each other. That matters doubly since the iOS actual assembles
     * GCM locally over the raw AES primitive (see AesGcm.ios.kt) — a
     * GHASH slip fails here on every target, including against the JVM's
     * JCE on the Android side. Routed through decryptBytes because
     * encryptHex draws a fresh random IV and cannot be pinned.
     */
    @Test
    fun decryptBytes_matchesPublishedGcmVectors() {
        val key = ByteArray(32)
        val zeroIvHex = "000000000000000000000000"
        // TC13 — empty plaintext under the all-zero key/IV: bare tag.
        assertEquals(0, cipher.decryptBytes(zeroIvHex + "530f8afbc74536b9a963b4f1c4cb738b", key).size)
        // TC14 — one all-zero block.
        val plaintext = cipher.decryptBytes(zeroIvHex + "cea7403d4d606b6e074ec5d3baf39d18" + "d0d1c8a799996bf0265b98b5d48ab919", key)
        assertTrue(plaintext.contentEquals(ByteArray(16)))
    }

    @Test
    fun encryptThenDecrypt_roundTrips() {
        val key = cipher.deriveKey("password", cipher.randomSaltHex(), 1)
        val plaintext = "provider://user:pass@host/path".encodeToByteArray()
        assertTrue(cipher.decryptBytes(cipher.encryptHex(plaintext, key), key).contentEquals(plaintext))
    }

    @Test
    fun encryptThenDecrypt_roundTripsEmptyPlaintext() {
        val key = cipher.deriveKey("password", cipher.randomSaltHex(), 1)
        assertEquals(0, cipher.decryptBytes(cipher.encryptHex(ByteArray(0), key), key).size)
    }

    /** A fresh IV per call — identical plaintext must not produce identical output. */
    @Test
    fun encryptHex_usesAFreshIvPerCall() {
        val key = cipher.deriveKey("password", saltHex, 1)
        val plaintext = "same input".encodeToByteArray()
        assertNotEquals(cipher.encryptHex(plaintext, key), cipher.encryptHex(plaintext, key))
    }

    /**
     * Tag mismatch must fail loudly. Both platforms throw, but not the
     * same type — Android surfaces `AEADBadTagException`, iOS an
     * `IllegalStateException` off the CommonCrypto status — so this
     * asserts only that it fails.
     */
    @Test
    fun decryptBytes_rejectsATamperedTag() {
        val key = cipher.deriveKey("password", saltHex, 1)
        val vector = "01ed42c927e0fc8b7e5ad3f6d99018af6e9b5664dfa2230a53bca91e610cfd94e55fe654e2b670be"
        val tampered = vector.dropLast(1) + if (vector.last() == 'a') 'b' else 'a'
        assertFails { cipher.decryptBytes(tampered, key) }
    }

    @Test
    fun decryptBytes_rejectsATamperedCiphertext() {
        val key = cipher.deriveKey("password", saltHex, 1)
        val vector = "01ed42c927e0fc8b7e5ad3f6d99018af6e9b5664dfa2230a53bca91e610cfd94e55fe654e2b670be"
        // Flip a nibble inside the ciphertext body (offset 24 = byte 12).
        val tampered = vector.take(24) + (if (vector[24] == 'a') 'b' else 'a') + vector.drop(25)
        assertFails { cipher.decryptBytes(tampered, key) }
    }

    @Test
    fun decryptBytes_rejectsTruncatedInput() {
        val key = cipher.deriveKey("password", saltHex, 1)
        assertFails { cipher.decryptBytes("00112233", key) }
    }

    @Test
    fun decryptBytes_rejectsOddLengthHex() {
        val key = cipher.deriveKey("password", saltHex, 1)
        assertFails { cipher.decryptBytes("012", key) }
    }

    // ---- Salt -------------------------------------------------------

    @Test
    fun randomSaltHex_is16BytesAndNotRepeating() {
        val a = cipher.randomSaltHex()
        assertEquals(32, a.length)
        assertNotEquals(a, cipher.randomSaltHex())
    }

    /** The salt round-trips through the same hex decoder the KDF uses. */
    @Test
    fun randomSaltHex_isAcceptedByDeriveKey() {
        assertEquals(32, cipher.deriveKey("password", cipher.randomSaltHex(), 1).size)
    }
}
