# YancoTV — R8 / ProGuard rules
#
# Stage 1.4 (2026-04-25): R8 baseline. `isMinifyEnabled = true` flips on for
# release builds; resource shrinking too. The bulk of correctness rules ship
# as consumer ProGuard rules inside library AARs (Sentry, Compose, Media3,
# OkHttp, Coil, etc.) — what's below is the additional set this app needs
# given its specific dependencies and reflection paths.
#
# Test by building `assembleRelease` and running the existing debug-only
# smoke tests against the release APK (after temporarily flipping the
# debug receivers to also live in release source set, or via a local-only
# debug-friendly build). Documented procedure in docs/build/r8-baseline.md.

# ─────────────────────────────────────────────────────────────────────
# General — preserve metadata downstream tools rely on
# ─────────────────────────────────────────────────────────────────────

# Reflection, enum lookup, kotlin-metadata, and serialization all need these.
-keepattributes Signature, InnerClasses, EnclosingMethod
-keepattributes *Annotation*
-keepattributes RuntimeVisibleAnnotations, RuntimeInvisibleAnnotations
-keepattributes RuntimeVisibleParameterAnnotations, RuntimeInvisibleParameterAnnotations
-keepattributes RuntimeVisibleTypeAnnotations, RuntimeInvisibleTypeAnnotations
-keepattributes Exceptions, SourceFile, LineNumberTable

# Stack-trace symbolication via Sentry uploads the mapping file (Stage 1.4
# follow-up). Renaming SourceFile is fine; Sentry restores the real name
# from the mapping. Without this attribute, R8 strips file names entirely
# and stack traces lose symbol context.
-renamesourcefileattribute SourceFile

# ─────────────────────────────────────────────────────────────────────
# Kotlinx Serialization
# Canonical rules adapted from
# https://github.com/Kotlin/kotlinx.serialization/blob/master/rules/common.pro
# Plus application-specific keep on our @Serializable types.
# ─────────────────────────────────────────────────────────────────────

-dontnote kotlinx.serialization.AnnotationsKt
-keepclassmembers class kotlinx.serialization.json.** {
    *** Companion;
}
-keepclasseswithmembers class kotlinx.serialization.json.** {
    kotlinx.serialization.KSerializer serializer(...);
}

# Synthetic $$serializer companions generated by the kotlinx-serialization
# compiler plugin for our @Serializable types in :shared. Without this R8
# strips them and Json.encodeToString throws SerializationException at
# runtime ("Serializer for class X is not found").
-keep,includedescriptorclasses class com.yancotv.shared.**$$serializer { *; }
-keepclassmembers class com.yancotv.shared.** {
    *** Companion;
}
-keepclasseswithmembers class com.yancotv.shared.** {
    kotlinx.serialization.KSerializer serializer(...);
}

# ─────────────────────────────────────────────────────────────────────
# Koin DI — module DSL reflection
# Koin core ships consumer rules but defensive -dontwarn covers optional
# integrations we don't pull in (compat, fragments, etc.).
# ─────────────────────────────────────────────────────────────────────

-dontwarn org.koin.android.compat.**
-dontwarn org.koin.androidx.scope.**

# ─────────────────────────────────────────────────────────────────────
# SQLDelight — runtime adapter resolution
# Consumer rules in app.cash.sqldelight:* handle the generated query
# classes; -dontwarn covers JDBC-related classes that Android doesn't have.
# ─────────────────────────────────────────────────────────────────────

-dontwarn app.cash.sqldelight.driver.jdbc.**

# ─────────────────────────────────────────────────────────────────────
# Ktor — consumer rules ship; -dontwarn for engine-specific optionals
# ─────────────────────────────────────────────────────────────────────

-dontwarn io.ktor.client.engine.darwin.**
-dontwarn io.ktor.client.engine.cio.**

# ─────────────────────────────────────────────────────────────────────
# Media3 — consumer rules ship; FFmpeg-specific keeps below
# ─────────────────────────────────────────────────────────────────────

# MK.9 (Stage 1.2) — FFmpeg ExoPlayer extension reflection target
# DefaultRenderersFactory loads the extension via reflection
# (`Class.forName("androidx.media3.decoder.ffmpeg.FfmpegAudioRenderer")`),
# so the classes have no static reference from app code and R8 would
# otherwise treat them as unused. Native methods need their JNI signatures
# intact too.
-keep class androidx.media3.decoder.ffmpeg.** { *; }
-keepclassmembers class androidx.media3.decoder.ffmpeg.** {
    native <methods>;
}

# Native libs themselves aren't subject to R8, but `LibraryLoader` resolves
# them by name via System.loadLibrary("ffmpegJNI") — keep that class so the
# reflective name lookup still works.
-keepclassmembers class androidx.media3.common.util.LibraryLoader {
    *;
}

# ─────────────────────────────────────────────────────────────────────
# Sentry — consumer rules ship; -dontwarn for optional NDK / OpenTelemetry
# integrations the app pulls transitively but doesn't enable.
# ─────────────────────────────────────────────────────────────────────

-dontwarn io.sentry.opentelemetry.**

# ─────────────────────────────────────────────────────────────────────
# YancoTV app surfaces
# ─────────────────────────────────────────────────────────────────────

# Activities, Application, BroadcastReceivers are referenced by name in
# AndroidManifest and kept automatically. No explicit rules needed.
#
# Documented for future reference:
#   com.yancotv.android.YancoApp
#   com.yancotv.android.MainActivity
#   com.yancotv.android.player.PlayerActivity
#   com.yancotv.android.reminders.ReminderAlarmReceiver
#   com.yancotv.android.reminders.ReminderBootReceiver
#   (debug receivers in src/debug/ never hit release variants — no rule)

# Koin's startKoin { modules(appModule) } pattern uses lambdas; the lambdas
# reference factory functions for service classes. Keeping them broadly
# would defeat R8 for the largest parts of our codebase. Instead we trust
# Koin's consumer rules + the fact that the lambda bodies create real
# references to the service classes — those references survive minification.
